[profile.default]
src = "src"
out = "out"
libs = ["../lib"]
test = "test"
script = "script"

# Compiler settings
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

# Testing
fuzz = { runs = 256 }
invariant = { runs = 256 }

[profile.ci]
fuzz = { runs = 1000 }
invariant = { runs = 1000 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
